### ISSUE TITLE
uninitialized constant Hydra::Works::Characterization::Base::BaseSchema

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-works#235]
```
uninitialized constant Hydra::Works::Characterization::Base::BaseSchema
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/hydra-works-b2f715f8c57f/lib/hydra/works/models/concerns/file_set/characterization/base.rb:13:in `block in <module:Base>'
activesupport (4.2.4) lib/active_support/concern.rb:120:in `class_eval'
activesupport (4.2.4) lib/active_support/concern.rb:120:in `append_features'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/hydra-works-b2f715f8c57f/lib/hydra/works/models/concerns/file_set/characterization.rb:13:in `include'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/hydra-works-b2f715f8c57f/lib/hydra/works/models/concerns/file_set/characterization.rb:13:in `block in <module:Characterization>'
activesupport (4.2.4) lib/active_support/concern.rb:120:in `class_eval'
activesupport (4.2.4) lib/active_support/concern.rb:120:in `append_features'
activesupport (4.2.4) lib/active_support/concern.rb:117:in `include'
activesupport (4.2.4) lib/active_support/concern.rb:117:in `block in append_features'
activesupport (4.2.4) lib/active_support/concern.rb:117:in `each'
activesupport (4.2.4) lib/active_support/concern.rb:117:in `append_features'
app/models/file_set.rb:3:in `include'
```

**Comment by jcoyne** [comment]
Perhaps because BaseSchema does not have a namespace? https://github.com/projecthydra-labs/hydra-works/blob/master/lib/hydra/works/models/characterization/base_schema.rb
