### ISSUE TITLE
undefined method `pcdm_object?' for nil:NilClass

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-works#240]
```
undefined method `pcdm_object?' for nil:NilClass

/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/hydra-pcdm-463d73a2fd4b/lib/hydra/pcdm/models/concerns/object_behavior.rb:43:in `select'
/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/hydra-pcdm-463d73a2fd4b/lib/hydra/pcdm/models/concerns/object_behavior.rb:43:in `in_objects'
/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-31684a3eb773/curation_concerns-models/app/models/concerns/curation_concerns/file_set/belongs_to_works.rb:11:in `generic_works'
/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-31684a3eb773/curation_concerns-models/app/models/concerns/curation_concerns/file_set/belongs_to_works.rb:16:in `generic_work_ids'
/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-31684a3eb773/curation_concerns-models/app/indexers/curation_concerns/file_set_indexing_service.rb:16:in `block in generate_solr_document'
/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-31684a3eb773/curation_concerns-models/app/indexers/curation_concerns/file_set_indexing_service.rb:6:in `tap'
/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-31684a3eb773/curation_concerns-models/app/indexers/curation_concerns/file_set_indexing_service.rb:6:in `generate_solr_document'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/active-fedora-9.4.3/lib/active_fedora/indexing.rb:23:in `to_solr'
```

**Comment by mjgiarlo** [comment]
Still relevant, @jcoyne?

**Comment by jcoyne** [comment]
Probably not
